#pragma kernel CountPixelsMain

Texture2D<float4> InputTexture; // input texture

RWStructuredBuffer<int> OutputBuffer;

#include "Assets/Shaders/include/ExposedSurface.cginc"

[numthreads(8,8,1)]
void CountPixelsMain(uint3 id : SV_DispatchThreadID)
{
    float4 input = InputTexture.Load(id);
    uint color = pack_uint(input);

    if (!is_valid(color)) return;
    int index = get_index(color);
    InterlockedAdd(OutputBuffer[index], 1);
}
